//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        public int recipe_ID { get; set; }
        public string title { get; set; }
        public string user_ID { get; set; }
        public string cateogry_ID { get; set; }
        public string difficulty { get; set; }
        public string time { get; set; }
        public string recipe_content { get; set; }
        public string recipe_date { get; set; }
        public string comment_ID { get; set; }
    }
}
