//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        public int recipe_ID { get; set; }
        public string title { get; set; }
        public string user_ID { get; set; }
        public Nullable<int> cateogry_ID { get; set; }
        public Nullable<int> difficulty { get; set; }
        public Nullable<int> time { get; set; }
        public string recipe_content { get; set; }
        public Nullable<System.DateTime> recipe_date { get; set; }
        public Nullable<int> comment_ID { get; set; }
        public byte[] picture { get; set; }
    }
}
